spring:
  cloud:
    function:
      definition: uppercase|sink
    stream:
      bindings:
        publisher-out-0:
          destination: example/processor/topic
        uppercaseSink-in-0:
          destination: example/processor/topic
          group: processor-group
