spring:
  cloud:
    function:
      definition: headerConsumer
    stream:
      bindings:
        headerPublisher-out-0:
          destination: example/headers/topic
        headerConsumer-in-0:
          destination: example/headers/topic
          group: headers-group
      solace:
        bindings:
          headerConsumer-in-0:
            consumer:
              headerExclusions: custom-org-id
