spring:
  cloud:
    function:
      definition: pausableConsumer
    stream:
      bindings:
        pausableConsumer-in-0:
          destination: example/pausable/topic
          group: pausable-group
      poller:
        fixed-delay: 1000
management:
  endpoints:
    web:
      exposure:
        include: bindings
