spring:
  cloud:
    function:
      definition: publisher;durableConsumer;anonConsumer
    stream:
      bindings:
        publisher-out-0:
          destination: example/groups/topic
        durableConsumer-in-0:
          destination: example/groups/topic
          group: durable-group
        anonConsumer-in-0:
          destination: example/groups/topic
      poller:
        fixed-delay: 2000
