spring:
  cloud:
    function:
      definition: manualAckConsumer
    stream:
      bindings:
        producer-out-0:
          destination: example/ack/topic
        manualAckConsumer-in-0:
          destination: example/ack/topic
          group: ack-group
      solace:
        bindings:
          manualAckConsumer-in-0:
            consumer:
              auto-bind-error-queue: true
