spring:
  cloud:
    function:
      definition: partitionedPublisher;partitionedConsumer
    stream:
      bindings:
        partitionedPublisher-out-0:
          destination: example/partitioned/topic
        partitionedConsumer-in-0:
          destination: example/partitioned/topic
          group: partitioned-group
          consumer:
            concurrency: 2

      solace:
        bindings:
          partitionedConsumer-in-0:
            consumer:
              provisionDurableQueue: true
