spring:
  cloud:
    function:
      definition: tracingPublisher;tracingConsumer
    stream:
      bindings:
        tracingPublisher-out-0:
          destination: example/tracing/topic
        tracingConsumer-in-0:
          destination: example/tracing/topic
          group: tracing-group
      poller:
        fixed-delay: 500
management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
