spring:
  cloud:
    function:
      definition: wildcardConsumer
    stream:
      bindings:
        wildcardConsumer-in-0:
          destination: example/dynamic/>
          group: dynamic-group
      poller:
        fixed-delay: 1000
